### ISSUE TITLE
Add batch request for itemDetails

### ISSUE THREAD

**Issue by matthias-luger** [Coflnet/SkyApi#10]
https://github.com/Coflnet/hypixel-react/issues/923 needs to request a lot of itemDetails in one go.
This currently results in a 429 "Too many Requests" Response. Please implement a batch request.

![Image](https://user-images.githubusercontent.com/58751503/193479681-0bfb01e9-84d9-40d2-8b0b-af6393788dd3.png)

**Comment by Ekwav** [comment]
Would you be okay with just a name lookup?

**Comment by matthias-luger** [comment]
@Ekwav Yeah that would be enough
