### ISSUE TITLE
Images do not exist

### ISSUE THREAD

**Issue by matthias-luger** [Coflnet/SkyApi#122]
Examples:

https://sky.coflnet.com/static/icon/TARANTULA_SILK
https://sky.coflnet.com/static/icon/NULL_OVOID
https://sky.coflnet.com/static/icon/ENCHANTED_PACKED_ICE
https://sky.coflnet.com/static/icon/MITE_GEL

**Comment by Ekwav** [comment]
fixed with https://github.com/Coflnet/SkyCommands/commit/d9464c4e6cd0c35efa79207b62bcc134c2e9d0c1
