### ISSUE TITLE
player search times out

### ISSUE THREAD

**Issue by Flou21** [Coflnet/SkyApi#28]
the player search times out

example command:
````
/ # curl http://sky-api.sky/api/search/player/Flou21
curl: (28) Failed to connect to sky-api.sky port 80 after 131204 ms: Operation timed out
````

pls fix

**Comment by Ekwav** [comment]
The port of the api is 8000

**Comment by Ekwav** [comment]
solved with https://github.com/Coflnet/k8s/commit/a43a0fc452e9392458aaa7ae3d64a70f608956a2
