### ISSUE TITLE
Filter check Validation Errors

### ISSUE THREAD

**Issue by Ekwav** [Coflnet/SkyApi#33]
The filter checking endpoint returns validation errors:

![Image](https://user-images.githubusercontent.com/58751503/226977179-0237a775-3825-4c61-af40-a88c098bb387.png)

![Image](https://user-images.githubusercontent.com/58751503/226977205-b060511e-ab6d-478d-a079-c135b15d18b0.png)

**Comment by Ekwav** [comment]
@matthias-luger what is this issue for?
The bidder is a UUID (string) not an object. Generally there are no filters for bidders currently because flips usually don't have bidders yet.

**Comment by matthias-luger** [comment]
Yeah, I sent you the format I use in the frontend. Work now
