### ISSUE TITLE
Mod auth sometimes returns HTTP 500

### ISSUE THREAD

**Issue by matthias-luger** [Coflnet/SkyApi#67]
An unexpected internal error occured. Please check that your request is valid. If it is please report the error and include reference '0e9e8e4ae99e2479b0d075a47f0007d0'.
Trace: sky--76f87fd6db-kwzln.0e9e8e4ae99e2479b0d075a47f0007d0

**Comment by Ekwav** [comment]
In that case thats because you didn't escape the newId passed to the request
